### ISSUE TITLE
Dealing with filetree history 

### ISSUE THREAD

**Issue by StephanEggermont** [pharo-vcs/tonel#1]
We can deal with filetree based history by replaying the commits.

**Comment by estebanlm** [comment]
how so?

**Comment by StephanEggermont** [comment]
The work Peter did for migrating smalltalkhub repos with history can be adapted for this.

**Comment by estebanlm** [comment]
I didn't know, but yes, good idea. 
I will see how to adapt my migration script... or better, I will ask Peter :)

**Comment by StephanEggermont** [comment]
Good idea. @peteruhnak Our ecosystem is too large to keep up with everything, even if you work on it full time.

**Comment by StephanEggermont** [comment]
https://github.com/peteruhnak/git-migration

**Comment by peteruhnak** [comment]
(Sidenote: there were some issues with loading git-migration because of GitFileTree; this is now resolved and GFT is no longer used.)

I think that git-migration can be adapted to migrate the entire history from filetree to tonel. Or rather than adapting, it can be forked to a new project, because 90% of the code is dealing with MCZ transformation to git.

I do not see any potential problem for having 100% 1:1 transformation from FileTree to tonel for the entire history, without too much work.

I imagine the following would be needed:

* take git history graph and convert it into a sequence of commits from oldest to newest; should be trivial
* adapt git-migration to read versions from Iceberg-backed repo. I am working with `MCVersion`, so if Iceberg provides this for git and contains all the necessary metadata (authors, dates, and parent commits) then it should be easy to do
* for each commit also include all non-code files... this is probably easy

The way I am writing right now is:

1. have a target repo that has a directory MemoryStore (otherwise I would murder disk with IO)
2. generate a sequence of MCVersions in the proper history/ancestral ordering
3. process all versions
    1. take a MCVersion from source repo, apply some metadata mapping (for mcz -> git), and write via a regular writer to the target repo (so this creates the files in the MemoryStore)
    2. take the MemoryStore content and create appropriate fast-import record

So for external files we would add another point between 3.i) and 3.ii)

* take all non-code files and copy them to the MemoryStore

**Comment by peteruhnak** [comment]
The aftermath that should be imho handled gracefully:

* all tags should be retagged
* forks downstream should be updated without too much hassle (some nice git script?)

**Comment by estebanlm** [comment]
ok, @peteruhnak fixed it here: https://github.com/peteruhnak/tonel-migration

we will apply it to Pharo later
