### ISSUE TITLE
parser is broken by literal array with square bracket

### ISSUE THREAD

**Issue by estebanlm** [pharo-vcs/tonel#18]
origin issue: https://pharo.fogbugz.com/f/cases/20659

When I accidentally encountered the code of TonelParser>>methodBody
a voice in my head told: it's too complex to be honest
So I decided to see how long it would take to attack...
Less than 5 minutes, see this test:

```Smalltalk
testMethodBodyWithSquareBracketInsideLiteralArray
    self 
        assertParse: '[ "What about this valid literal Array guys" ^#( [ ) ]'
        rule: #methodBody
        equals: ' "What about this valid literal Array guys" ^#( [ ) '.
```

If ever you manage to fix it, I have more for you

```Smalltalk
testMethodBodyWithCommentNextToDollarCharLiteral
    self 
        assertParse: '[^$$"what about this one]"]'
        rule: #methodBody
        equals: '^$$"what about this one]"'.
```

**Comment by dalehenrich** [comment]
just a wild thought but what about making leading white space for method source a requirement and the enclosing brackets are on lines by themselves:

```
[
  "What about this valid literal Array guys" ^#( [ ) 
]
```
... and the parser chokes with a meaningful error if there is a non `[]` character in method body...

It's not quite ideal, but it does mean that the extraction of method is fast and humans can learn to follow the rule ... only folks who don't believe in whitespace will be unhappy:)

**Comment by estebanlm** [comment]
heh... **I** do not believe in whitespace ;)
I have already a fix for both cases, I'm refactoring to get it right (into a new class `TonelSourceScanner`)

**Comment by dalehenrich** [comment]
... i don't like it either:) but compromises have to be made somewhere ... BTW, I also prefer the parsing approach, because the source needs to be unadulterated ... martin mentioned that you are also eliminating symbols from the meta data ... have you made those changes as well ... I already went through and added asSymbol is the few places where GemStone uses strings, so I'll have to clean that up, too:)

**Comment by estebanlm** [comment]
yeah, I have an already working version: just ugly and needs refactor before committing. 
about the categories: I told Martin I'm ok with that (basically, it does not changes anything to me so if you guys prefers it, I'm fine with it). But I still didn't have the time to implement it :)
(I need to add an issue, btw)

**Comment by nicolas-cellier-aka-nice** [comment]
this issue should be reopened because the fix is too simplistic...
Imagine that I have a method like this:

    closingChars
        ^#( $) ] } )

then current fix will detect the end of literal array just after $), which is not OK.
Also I can put comment or string inside litral arrays...

    closingExpressions
        ^#( "note that we need to prefix ) with $, but this is not necessary for ] and }"
              ')]}' $) ] }
        )

And code like above could really exist!

That's what I don't like about the Tonel format, it must be too much aware of Smalltalk syntax.
If I want to implement some extensions like Dolphin ##( ) then there will be yet another syntax in the literal array...

**Comment by estebanlm** [comment]
yes, it could. 
At a point, the real implementable solution for us is to use RBParser to solve the parsing and just forget about it... but then it will not be portable anymore :)

**Comment by nicolas-cellier-aka-nice** [comment]
Yes, RBParser would likely kill cross-dialect portability.
I suggest that we parse the literal array more thoroughly with same kind of hacks as upper level

- recognize and skip comments
- recognize and skip strings
- recognize and skip chars

maybe it'll be enough (until someone find an even uglier piece of syntactically valid Smalltalk)

**Comment by nicolas-cellier-aka-nice** [comment]
Oh, but I see that it is already doing this... Only the Character literal test is missing.

So maybe just a $ protection should do it

    scanForLiteralArrayIfMatch: aBlock
	| literalCount |

	self isStartingLiteralArray ifFalse: [ ^ self ]. 
	literalCount := 1.
	self readUntil: [  
		self scanForStringIfMatch: [].
		self scanForCommentIfMatch: [].
		(char = $( and: [prevChar ~= $$]) ifTrue: [ literalCount := literalCount + 1 ].
		(char = $) and: [prevChar ~= $$]) ifTrue: [ literalCount := literalCount - 1 ].
		literalCount = 0 ].
	aBlock value

**Comment by nicolas-cellier-aka-nice** [comment]
Unfortunately, the `(prevChar ~= $$)` test is also too simplistic.
Inside a literal array #( ... ), nothing prevents a $$ to be immediately followed by another character...

The most simple counter example is

    literalCharacterPrefix
        ^#($$)

More complex ones are:

    ^#( $$'please use space before this string)('$$"please use space before this comment or avoid putting a ] in it"$$(this really is a literal array with a ] in it))

The problem is not only inside literal, it is also in blocks:

    maybeReturnADollar
        self testSomething ifTrue: [^$$]

Which just mean that literal char ($) must be properly parsed, like literal array, string and comments already are...

**Comment by nicolas-cellier-aka-nice** [comment]
Solution is to properly parse literal char, then simplify (remove) prevChar tests like this:

    isStartingLiteralCharacter
	"A literal Character start with a dollar sign in Smalltalk syntax"  
	^ char = $$

    isStartingComment
	"Comment start with a double quote in Smalltalk syntax"
	^ char = $"

    isStartingString
	"String start with single quote in Smalltalk syntax"
	^ char = $'

    scanForLiteralArrayIfMatch: aBlock
	| literalCount |
	self isStartingLiteralArray ifFalse: [ ^ self ]. 
	literalCount := 1.
	self readUntil: [
		self scanForLiteralCharacterIfMatch: [].
		self scanForStringIfMatch: [].
		self scanForCommentIfMatch: [].
		char = $( ifTrue: [ literalCount := literalCount + 1 ].
		char = $) ifTrue: [ literalCount := literalCount - 1 ].
		literalCount = 0 ].
	aBlock value

    scanForLiteralCharacterIfMatch: aBlock
	self isStartingLiteralCharacter ifFalse: [ ^ self ]. 
	self readNext.
	char := prevChar := Character null.
	^aBlock value

    scanNextChunk
	self readNext.
	self scanForLiteralCharacterIfMatch: [].
	self scanForBlockIfMatch: [ ^ self ].
	self scanForCommentIfMatch: [ ^ self ].
	self scanForStringIfMatch: [ ^ self ].
	self scanForLiteralArrayIfMatch: [ ^ self ]

The parser code is a bit simpler and more robust...
It still knows too much about Smalltalk syntax, but that we cannot fix, it is flawed by design.
